version: "3"
services:
  javamongodb:
    image: mongo:latest
    container_name: javamongodb
    ports:
      - 27017:27017
  todoappmongodb:
    image: todoappmongodb:1.0
    container_name: todoappmongodb
    ports:
      - 8080:8080
    links:
      - javamongodb